### ISSUE TITLE
Allow for multiple default archivers in AA plugin

### ISSUE THREAD

**Issue by tynanford** [ChannelFinder/ChannelFinderService#144]
It would be useful for our site if the `aa.default_alias` property is a list instead of single archiver alias. We have two appliance instances and would like PVs by default to be placed in each instance.

It wouldn't be much more effort to allow comma separated lists in the `archiver` info tag as well but that isn't needed for us. Does that make sense to add or not?

**Comment by shroffk** [comment]
I see no harm in the default_alias being a list. ( it does complicate things... since now you have to match a list of aliases to the list of aa urls... should we just support something like "all" defined url's )

regarding the archiver info tag... I think it should support the same features that the default alias supports. i.e. a single archiver url or a list ( I am guessing we only need to make changes to the processor )

**Comment by tynanford** [comment]
> should we just support something like "all" defined url's

That could be a nice feature but it doesn't fit our use case at ALS. I am thinking to keep that a separate issue/PR than this one unless you think I should add it

with #145 the archiver tag can now be a list of archivers too
