### ISSUE TITLE
Elasticsearch 7.9.2 support?

### ISSUE THREAD

**Issue by geniejhang** [ChannelFinder/ChannelFinderService#20]
@shroffk Hi.
I'm curious if there's a plan to support elasticsearch 7.x version.
FYI, I tested with 7.9.2 by removing mapping types for each index and it just worked.

https://github.com/geniejhang/ChannelFinder-SpringBoot/commit/4c32018ff6e0137b7808ff36a083ecb4e6deddfe

**Comment by kasemir** [comment]
On Mac OS X, running elastic 6.x is no longer possible.

6-3-2 only runs with Java 8.
Even then, it stops because some new rules in Mac OS prevent running code not bought from the apple store:
https://github.com/elastic/elasticsearch/issues/49664,
https://github.com/elastic/elasticsearch/issues/48490.

7-9-2 comes with variants for Mac OS, Linux, Windows and runs fine, but has changes related to mapping types, causing mapping_definitions.sh to fail unless one adds `?include_type_name=true` to the URLs in there.

Does anybody understand the details of what's described in https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html ?

Will "removing mapping types" work with ES 7 as well as ES 8, where the "include_type_name" parameter will be removed?

**Comment by kasemir** [comment]
@geniejhang , will your "removing mapping types" for ES 7 break support for ES 6?
So it's one or the other?
We're just starting to look at it, and would be all for supporting ES 7, since ES 6 just won't run with JDK 15, Mac OS, ..
But I guess people are operating with ES 6, so can't break that...

**Comment by geniejhang** [comment]
@kasemir I've never tested it, but as long as I understand, they fixed type "_doc" and made it invisible.
So, my guess is that with the old version of Java API, just replacing type name to "_doc" should work.

**Comment by shroffk** [comment]
> So, my guess is that with the old version of Java API, just replacing type name to "_doc" should work.

I did some tests and this might work

**Comment by jeonghanlee** [comment]
Any update or any plan to move forward?

**Comment by kasemir** [comment]
Good question. I'm a user not a developer on this and still unclear about the details.

As far as I understand:

 * Everything works with elastic version 6, and people use that in production, can't break it.
 * You can use elastic 7 after patching mapping_definitions.sh, add `?include_type_name=true` to the URLs in there. That's an easy workaround, but will fail with elastic 8.
 * @geniejhang has a larger code change that makes it work with elastic 7 and I think 8. Don't know if it would still support elastic 6.

Is there one solution for elastic 6 to 8?
If not, patching  mapping_definitions.sh looks like the simplest way to run under elastic 7.

**Comment by kasemir** [comment]
If patching mapping_definitions.sh is an acceptable solution for now,  could probably include that in there:
```
if [ .. elastic version .. -gt 6 ]
then
   URL = "$URL?include_type_name=true"
fi
```

**Comment by shroffk** [comment]
Currently my plan is to stay with elastic 6 for some more time. I know that we can't run it on Mac OS but I am assuming that most setup of ChannelFinder are on linux servers.
I don't see any significant advantages with elastic 7 to necessitate an immediate move and would rather directly move to elastic 8. We can update the mapping and the code to completely remove the type references in one go.

In the meanwhile we can include the above patch.

**Comment by geniejhang** [comment]
FRIB is trying to move the latest ES 7.x to reduce maintenance work instead of going directly from ES 6 to 8.

**Comment by shroffk** [comment]
we have moved to elastic 8
